### ISSUE TITLE
Add social networks links

### ISSUE THREAD

**Issue by medchedli** [ISTIC-DevSpace/DevSpace-Landing-Page#5]
@neH9

**Comment by neH9** [comment]
NO

**Comment by abdelhedydev** [comment]
I am here

**Comment by nour-l** [comment]
Welcome hhh

**Comment by Bujupah** [comment]
is there anyone still working on this page ? is it even alive? can i work on it :vertical_traffic_light:  ?

**Comment by medchedli** [comment]
@Bujupah of course Khalil please feel free to submit your suggestions and ideas. However, the hosting account is suspended that's why we are thinking to switch to GitHub Pages ( https://pages.github.com/ ) for now and start working on a better version ASAP

**Comment by medchedli** [comment]
@yessinebouriga @LazyFatArrow any other volunteers here ?

**Comment by yessinebouriga** [comment]
I'm in i can help too

**Comment by LazyFatArrow** [comment]
@medchedli what are the requirements?

**Comment by LazyFatArrow** [comment]
@medchedli Can you make a Trello Board where we can add requirements and tasks from there like:
features, todo, doing, done

**Comment by medchedli** [comment]
@LazyFatArrow let's do it on GitHub Project instead https://github.com/ISTIC-DevSpace/DevSpace-Landing-Page/projects/1

**Comment by medchedli** [comment]
I will try to submit some of the ideas that I have to create an initial backlog ( some of them we already discussed in Discord ). @LazyFatArrow @yessinebouriga @Bujupah you can start brainstorming, determining the technology to use and creating a task list on GitHub Projects section.

**Comment by LazyFatArrow** [comment]
@medchedli  Alright

**Comment by yessinebouriga** [comment]
nice just wait for exams @medchedli  and we'll discuss technologies , tasks,roles me and @Bujupah  and @LazyFatArrow  i think that @samibenabderazak  is interested too and can help us
